language: python
python:
  - "2.7"
  - "3.4"

env:
  - TOX_SUITE=py27
  - TOX_SUITE=py34
  - TOX_SUITE=pep8
  - TOX_SUITE=coverage

install: pip install tox coveralls

after_success:
    - coveralls

script: tox -e$TOX_SUITE